[colors.primary]
background = "#000000"
foreground = "#ebdbb2"

[font]
size = 9

[font.normal]
family = "Hack Nerd Font Mono"

[[keyboard.bindings]]
key = "NumpadEnter"
chars = "\n"

[shell]
program = "/opt/homebrew/bin/fish"
#
# [window]
# opacity = 0.5
# blur = true

# [mouse]
# hide_when_typing = true

[cursor.style]
blinking = "Always"
