set nocompatible
filetype off

"{{{ PLUGINS
call plug#begin()
Plug 'jiangmiao/auto-pairs'
Plug 'itchyny/lightline.vim'
Plug 'godlygeek/tabular'
Plug 'w0rp/ale'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all'}
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-vinegar'      "better netrw
Plug 'tpope/vim-abolish'      "toggle casing (snake or camel) with crs and crc
Plug 'tpope/vim-dispatch'     "provides :Make and :Start
Plug 'tpope/vim-surround'     "provides mappings to surround stuff with stuff
Plug 'tpope/vim-commentary'   "mappings to comment/uncomment blocks of code
Plug 'tpope/vim-sleuth'       "automagically adjusts tab width
Plug 'tpope/vim-repeat'       "enables repeating commands from plugins
Plug 'ervandew/supertab'
Plug 'schickling/vim-bufonly'
Plug 'majutsushi/tagbar'
Plug 'machakann/vim-highlightedyank'
Plug 'majutsushi/tagbar'
Plug 'tpope/vim-rails',           { 'for': 'ruby' }
Plug 'mattn/emmet-vim',           { 'for': ['vue', 'html'] }
Plug 'cespare/vim-toml',          { 'for': 'toml' }
Plug 'davidhalter/jedi-vim',      { 'for': 'python' }
Plug 'digitaltoad/vim-pug',       { 'for': ['pug', 'jade', 'vue'] }
Plug 'posva/vim-vue',             { 'for': 'vue' }
Plug 'fatih/vim-go',              { 'for': 'go' }
Plug 'rust-lang/rust.vim',        { 'for': 'rust' }
Plug 'leafgarland/typescript-vim',{ 'for': 'typescript' }
Plug 'pangloss/vim-javascript',   { 'for': 'javascript' }
Plug 'morhetz/gruvbox'
Plug 'Shougo/neosnippet.vim'
Plug 'Shougo/neosnippet-snippets'
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
call plug#end()
"}}}

filetype plugin indent on

"{{{ GENERAL
syntax enable
set re=1
set shortmess+=c
set timeoutlen=1000 ttimeoutlen=0
let g:ftplugin_sql_omni_key = '<C-j>'
set encoding=utf-8
set shell=/usr/bin/fish
set cmdheight=2
set number relativenumber
set hid
set colorcolumn=100
set guifont=monospace
set nobk
set textwidth=100
set noswapfile
if (has("nvim"))
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif
set lazyredraw
set termguicolors
set background=dark
colorscheme gruvbox
set signcolumn=yes
set tabstop=2
set shiftwidth=2
set expandtab
set backspace=indent,eol,start
set autoindent
set wrap
set pastetoggle=<leader>z
set clipboard=unnamed
set ignorecase
set history=100
set hlsearch
set showmatch
set wildmenu
set updatetime=100
set autoread
set ttyfast
" set t_Co=256
" set t_ut=
set mouse=a
let mapleader = ','

let g:netrw_list_hide= '.*\.swp$,.DS_Store,*/tmp/*,*.so,*.swp,*.swo,*.zip,*.git,^\.\.\=/\=$'
let g:python_host_prog="/usr/bin/python2.7"
let g:python3_host_prog="/usr/bin/python3"

au FileType java set list listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·

set fdm=expr
set fde=getline(v:lnum)=~‘^\\s\/\/‘?1:getline(prevnonblank(v:lnum))=~‘^\\s\/\/‘?1:getline(nextnonblank(v:lnum))=~‘^\\s*\/\/’?1:0
set foldmethod=expr |
        \ set foldexpr=getline(v:lnum)=~'^\\s*//' |
        \ exe "normal zM``"

augroup netrw_buf_hidden_fix
  autocmd!
  set nohidden
  autocmd BufWinEnter *
        \  if &ft != 'netrw'
        \|     set bufhidden=hide
        \| endif
augroup end

" highlight extra whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()
"}}}

" {{{ VIM-MARKDOWN
let g:markdown_fenced_languages = ['rust', 'go']
" }}}

"{{{ TAGBAR
let g:tagbar_foldlevel = 0
"}}}

"{{{ LIGHTLINE
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'colorscheme': 'gruvbox',
      \ 'component_function': {
      \   'gitbranch': 'fugitive#head',
      \ },
      \ }
set laststatus=2
set noshowmode
"}}}

" {{{ FUGITIVE
set diffopt+=vertical
" }}}

" {{{ SUPERTAB
let g:SuperTabDefaultCompletionType = "<c-n>"
" }}}

" {{{ FZF
imap <c-x><c-k> <plug>(fzf-complete-word)
imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-l> <plug>(fzf-complete-line)
nmap <leader><tab> <plug>(fzf-maps-n)

command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".<q-args>, <bang>0)
command! -bang -nargs=? -complete=dir Files
 \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)
" }}}

" {{{ BETTER WHITESPACE
let g:better_whitespace_enabled=1
let g:strip_whitespace_on_save=1
" }}}

" {{{ ALE
let g:ale_fixers = {
      \ 'javascript': ['eslint'],
      \ 'dart': ['dartfmt'],
      \ 'python': ['autopep8', 'isort'],
      \ 'cpp': ['clang-format'],
      \ 'html': ['prettier'],
      \ 'css': ['prettier'],
      \ 'ruby': ['rubocop'],
      \ 'c': ['uncrustify'],
      \ 'rust': ['rustfmt'],
      \ 'vue': ['eslint'],
      \ '*': ['trim_whitespace']
      \}
let g:ale_fix_on_save = 1
let g:ale_lint_on_enter = 1
let g:ale_emit_conflict_warnings = 1
let g:ale_rust_cargo_use_clippy = 1
let g:ale_go_gometalinter_options = '--fast'
let g:ale_linters = {
      \ 'javascript': ['eslint'],
      \ 'typescript': ['tslint'],
      \ 'vue': ['tslint', 'vls'],
      \ 'go': ['vet', 'errcheck', 'lint'],
      \ 'python': ['flake8'],
      \ 'cpp': ['clangd'],
      \ 'c': ['clang']
      \}
"}}}

" " {{{ NEOSNIPPET
"   let g:neosnippet#enable_snipmate_compatibility = 1

"   imap <C-k>     <Plug>(neosnippet_expand_or_jump)
"   smap <C-k>     <Plug>(neosnippet_expand_or_jump)
"   xmap <C-k>     <Plug>(neosnippet_expand_target)

"   imap <expr><TAB>
"    \ pumvisible() ? "\<C-n>" :
"    \ neosnippet#expandable_or_jumpable() ?
"    \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
"   smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
"   \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

"   if has('conceal')
"     set conceallevel=0 concealcursor=niv
"   endif
" " }}}

" {{{ MAPPINGS
command! WQ wq
command! Wq wq
command! W w
command! Q q
nnoremap <silent> <F3> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
nnoremap <S-F5> ggvG=
nnoremap Q @q
nnoremap 0 ^
nnoremap ^ 0
nnoremap Q :norm @q<cr>
nnoremap gev :e $MYVIMRC<CR>
nnoremap gsv :so $MYVIMRC<CR>
nnoremap <LeftMouse> <NOP>
nnoremap <leader>ls :buffers<CR>:buffer<Space>
nnoremap <Left> <NOP>
nnoremap <Right> <NOP>
nnoremap <Up> <NOP>
nnoremap <Down> <NOP>
nmap <tab> :bnext<CR>
nmap <s-tab> :bprevious<CR>
nmap <c-p> :Files<CR>
nmap <c-f> :Rg<space>
nmap <leader>en :ALENext<CR>
nmap <leader>ep :ALEPrevious<CR>
nmap <leader>o :only<CR>
nmap <leader>bd :bdelete<CR>
nmap <leader>bq :bdelete!<CR>
nmap <leader>ba :bufdo bd<CR>
nmap <leader>bo :BufOnly<CR>
nmap <leader>f :ALEFix<CR>
nmap <leader>S :,$s/\<<C-r><C-w>\>//gc<Left><Left><Left>
nmap <leader>s :%s/\<<C-r><C-w>\>//gc<Left><Left><Left>
nmap <leader>w :!surf "duckduckgo.com?q="&<Left><Left>
nmap <leader>pj :norm 0v$,json<CR>
nmap <leader>e :!
nmap <leader>be :!<UP><CR>
nmap <leader>x :%!xxd<CR>
nmap <C-v><C-v> gg<C-V>G$
nmap <c-s><c-v> :vsplit<CR>
nmap <c-s><c-h> :split<CR>
nmap ,. :TagbarToggle<CR><C-w><C-w>
nmap <Down> :cnext<cr>
nmap <Up> :cprevious<cr>
nmap <space> ,
nmap <space><space> :e#<cr>
noremap <Left> <NOP>
noremap <Right> <NOP>
inoremap <C-c> <ESC>
inoremap <LeftMouse> <NOP>
vnoremap <leader>pj :!python -m json.tool<CR>

if has('nvim')
  tnoremap <leader>bd :bd!<CR>
endif

augroup qf
   autocmd!
   autocmd FileType qf set nobuflisted
augroup END
"}}}

"{{{ VIM-LSP
" let g:lsp_log_file = expand('~/Desktop/vim-lsp.log')
let g:asyncomplete_auto_popup = 1
let g:lsp_diagnostics_enabled = 0
imap <c-space> <Plug>(asyncomplete_force_refresh)

au User lsp_setup call lsp#register_server({ 'name': 'gopls', 'cmd': {server_info->['gopls']}, 'whitelist': ['go'] })
autocmd FileType go setlocal omnifunc=lsp#complete

au User lsp_setup call lsp#register_server({ 'name': 'javascript-ls', 'cmd': {server_info->['javascript-typescript-stdio']}, 'whitelist': ['javascript', 'typescript'] })
autocmd FileType javascript setlocal omnifunc=lsp#complete
autocmd FileType typescript setlocal omnifunc=lsp#complete

au User lsp_setup call lsp#register_server({ 'name': 'ra_lsp_server', 'cmd': {server_info->['rls']}, 'whitelist': ['rust'] })
autocmd FileType rust setlocal omnifunc=lsp#complete

nnoremap <F5> :LspCodeAction<CR>
nnoremap <silent> K :LspHover<CR>
nnoremap <silent> gd :LspDefinition<CR>
nnoremap <silent> gi :LspImplementation<CR>
nnoremap <silent> gr :LspReferences<CR>
nnoremap <silent> R :LspRename<CR>
"}}}

function! ProfileStart()
  :profile start profile.log
  :profile func *
  :profile file *
endfunction

function! ProfileEnd()
  :profile pause
  :noautocmd qall!
endfunction
