set nocompatible
filetype off

"{{{ PLUGINS
call plug#begin()
Plug 'itchyny/lightline.vim'
Plug 'godlygeek/tabular'
Plug 'dense-analysis/ale'
Plug 'Raimondi/delimitMate'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all'}
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-vinegar'      "better netrw
Plug 'tpope/vim-abolish'      "toggle casing (snake or camel) with crs and crc
Plug 'tpope/vim-dispatch'     "provides :Make and :Start
Plug 'tpope/vim-surround'     "provides mappings to surround stuff with stuff
Plug 'tpope/vim-commentary'   "mappings to comment/uncomment blocks of code
Plug 'tpope/vim-repeat'       "enables repeating commands from plugins
Plug 'ervandew/supertab'
Plug 'schickling/vim-bufonly'
Plug 'majutsushi/tagbar'
Plug 'tpope/vim-rails',           { 'for': 'ruby' }
Plug 'mattn/emmet-vim',           { 'for': ['vue', 'html', 'xml'] }
Plug 'cespare/vim-toml',          { 'for': 'toml' }
Plug 'davidhalter/jedi-vim',      { 'for': 'python' }
Plug 'digitaltoad/vim-pug',       { 'for': ['pug', 'jade', 'vue'] }
Plug 'posva/vim-vue',             { 'for': 'vue' }
Plug 'fatih/vim-go',              { 'for': 'go' }
Plug 'rust-lang/rust.vim',        { 'for': 'rust' }
Plug 'leafgarland/typescript-vim',{ 'for': 'typescript' }
Plug 'pangloss/vim-javascript',   { 'for': 'javascript' }
Plug 'udalov/kotlin-vim',         { 'for': 'kotlin' }
Plug 'Shougo/neosnippet.vim'
Plug 'Shougo/neosnippet-snippets'
Plug 'roxma/nvim-yarp'

Plug 'neoclide/coc.nvim', {'branch': 'release'}

Plug 'chriskempson/base16-vim'
Plug 'morhetz/gruvbox'
call plug#end()
"}}}

filetype plugin indent on

"{{{ GENERAL
syntax enable
set re=1
set shortmess+=c
set timeoutlen=1000 ttimeoutlen=0
let g:ftplugin_sql_omni_key = '<C-j>'
set encoding=utf-8
set shell=/usr/bin/fish
set cmdheight=2
set number relativenumber
set hid
set colorcolumn=100
set guifont=monospace
set nobk
set noswapfile
if (has("nvim"))
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif
set lazyredraw
set termguicolors
set background=dark
colorscheme base16-gruvbox-dark-hard
set t_Co=256
set signcolumn=yes
set tabstop=2
set shiftwidth=2
set expandtab
set backspace=indent,eol,start
set autoindent
set pastetoggle=<leader>z
set clipboard=unnamed
set ignorecase
set history=100
set hlsearch
set showmatch
set wildmenu
set updatetime=100
set autoread
set ttyfast
set mouse=a
let mapleader = ','
let maplocalleader = "\\"
let g:python_host_prog="/usr/bin/python2.7"
let g:python3_host_prog="/usr/bin/python3"

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()
"}}}

" {{{ VIM-MARKDOWN
let g:markdown_fenced_languages = ['rust', 'go']
" }}}

"{{{ TAGBAR
let g:tagbar_foldlevel = 0
"}}}

"{{{ LIGHTLINE
let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'cocstatus', 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'cocstatus': 'coc#status',
      \   'gitbranch': 'fugitive#head',
      \ },
      \ }
set laststatus=2
set noshowmode
"}}}

" {{{ FUGITIVE
set diffopt+=vertical
" }}}

" {{{ SUPERTAB
let g:SuperTabDefaultCompletionType = "<c-n>"
" }}}

" {{{ FZF
imap <c-x><c-k> <plug>(fzf-complete-word)
imap <c-x><c-f> <plug>(fzf-complete-path)
imap <c-x><c-l> <plug>(fzf-complete-line)
nmap <leader><tab> <plug>(fzf-maps-n)

command! -bang -nargs=* Rg call fzf#vim#grep("rg --column --line-number --no-heading --color=always --smart-case ".<q-args>, <bang>0)
command! -bang -nargs=? -complete=dir Files
 \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)
" }}}

" {{{ ALE
      " \ 'cpp': ['clang-format'],
let g:ale_fixers = {
      \ 'javascript': ['eslint'],
      \ 'typescript.tsx': ['eslint'],
      \ 'typescript': ['eslint'],
      \ 'go': ['goimports'],
      \ 'python': ['autopep8', 'isort'],
      \ 'html': ['prettier'],
      \ 'css': ['prettier'],
      \ 'ruby': ['rubocop'],
      \ 'kotlin': ['ktlint'],
      \ 'c': ['uncrustify'],
      \ 'rust': ['rustfmt'],
      \ 'vue': ['eslint'],
      \ '*': ['trim_whitespace']
      \}

autocmd BufNewFile,BufRead *.tsx setlocal filetype=typescript.tsx
let g:ale_kotlin_ktlint_options = '--experimental'
let g:ale_completion_enabled = 1
let g:ale_disable_lsp = 1
let g:ale_fix_on_save = 1
let g:ale_lint_on_enter = 1
let g:ale_emit_conflict_warnings = 1
let g:ale_rust_cargo_use_clippy = 1
let g:ale_go_gometalinter_options = '--fast'
let g:ale_linters = {
      \ 'javascript': ['eslint'],
      \ 'typescript': ['tslint'],
      \ 'kotlin': ['ktlint'],
      \ 'cpp': [],
      \ 'vue': ['tslint', 'vls'],
      \ 'go': ['vet', 'errcheck', 'lint'],
      \ 'python': ['flake8']
      \}
"}}}

" {{{ NEOSNIPPET
  let g:neosnippet#enable_snipmate_compatibility = 1

  imap <C-k>     <Plug>(neosnippet_expand_or_jump)
  smap <C-k>     <Plug>(neosnippet_expand_or_jump)
  xmap <C-k>     <Plug>(neosnippet_expand_target)

  imap <expr><TAB>
   \ pumvisible() ? "\<C-n>" :
   \ neosnippet#expandable_or_jumpable() ?
   \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
  \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

  if has('conceal')
    set conceallevel=0 concealcursor=niv
  endif
" }}}

" {{{ TAGBAR
nmap ,. :TagbarToggle<CR><C-w><C-w>
" }}}

" {{{ MAPPINGS
function! ProfileStart()
  :profile start profile.log
  :profile func *
  :profile file *
endfunction

function! ProfileEnd()
  :profile pause
  :noautocmd qall!
endfunction

command! WQ wq
command! Wq wq
command! W w
command! Q q
nnoremap <silent> <F3> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
nnoremap gev :e $MYVIMRC<CR>
nnoremap gsv :so $MYVIMRC<CR>
nnoremap <leader>ls :buffers<CR>:buffer<Space>
nnoremap <LeftMouse> <NOP>
nnoremap <Left> <NOP>
nnoremap <Right> <NOP>
nnoremap <Up> <NOP>
nnoremap <Down> <NOP>
nmap <tab> :bnext<CR>
nmap <s-tab> :bprevious<CR>
nmap <c-p> :GFiles<CR>
nmap <c-l> :Buffers<CR>
nmap <c-f> :Rg<space>
nmap <leader>f :ALEFix<CR>
nmap <leader>dn :ALENext<CR>
nmap <leader>dp :ALEPrevious<CR>
nmap <leader>ba :bufdo bd<CR>
nmap <leader>o :only<CR>
nmap <leader>bo :bo<CR>
nmap <leader>S :,$s/\<<C-r><C-w>\>//gc<Left><Left><Left>
nmap <leader>s :%s/\<<C-r><C-w>\>//gc<Left><Left><Left>
nmap <leader>w :!surf "duckduckgo.com?q="&<Left><Left>
nmap <leader>e :!
nmap <leader>be :!<UP><CR>
nmap <leader>x :%!xxd<CR>
nmap <C-v><C-v> gg<C-V>G$
nmap <c-s><c-v> :vsplit<CR>
nmap <c-s><c-h> :split<CR>
nmap <Down> :cnext<cr>
nmap <Up> :cprevious<cr>
nmap <space> ,
nmap <space><space> :e#<cr>
noremap <Left> <NOP>
noremap <Right> <NOP>
map <C-c> <ESC>
inoremap <LeftMouse> <NOP>
vnoremap <leader>pj :!python -m json.tool<CR>
"}}}

" {{{ COC.NVIM
inoremap <silent><expr> <TAB>
  \ pumvisible() ? "\<C-n>" :
  \ <SID>check_back_space() ? "\<TAB>" :
  \ coc#refresh()

nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

nmap <silent>ca  <Plug>(coc-codeaction)
xmap <leader>ca  <Plug>(coc-codeaction-selected)

nnoremap <silent> K :call <SID>show_documentation()<CR>
nmap <silent>R <Plug>(coc-rename)

autocmd CursorHold * silent call CocActionAsync('highlight') " highlight symbol under cursor

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

nnoremap <silent> <space>a  :<C-u>CocList diagnostics<cr>
nnoremap <silent> <space>e  :<C-u>CocList extensions<cr>
nnoremap <silent> <space>c  :<C-u>CocList commands<cr>
nnoremap <silent> <space>o  :<C-u>CocList outline<cr>
nnoremap <silent> <space>s  :<C-u>CocList -I symbols<cr>
nnoremap <silent> <space>j  :<C-u>CocNext<CR>
nnoremap <silent> <space>k  :<C-u>CocPrev<CR>
nnoremap <silent> <space>p  :<C-u>CocListResume<CR>
" }}}
